### ISSUE TITLE
Como usuario quiero registrarme en la aplicación para usarla

### ISSUE THREAD

**Issue by bequipedia** [bequipedia/optitask-frontend#2]

**Comment by maruchf** [comment]
Incorporar un inicio de sesión y registro con diseño sencillo (ver ejemplo)

1. Debe validar campos completos:
- Nombre
- Apellido
- Correo 
- Fecha de nacimiento
- Usuario (NickName)
- Contraseña
- Validar contraseña

2. Estructura de correo: (Usar API para validar estructura de correo)
3. Confirmación de contraseña (Validar que es la misma en los 2 campos)

![Inicio de sesión (parecido a esto)](https://user-images.githubusercontent.com/72889569/106953455-ca844f00-6708-11eb-8de6-dada70a37cf2.JPG)
